### ISSUE TITLE
Add links to the database table for software

### ISSUE THREAD

**Issue by patrick91** [patrick91/latest.cat#21]
<img width="787" alt="image" src="https://user-images.githubusercontent.com/667029/161142218-41308026-fd11-4634-a0af-3c87da78dcc7.png">

```yaml
- slug: go
  name: Go
  aliases: [golang]
  source: github
  repository: golang/go
  version_naming: go
  links:
    - name: docs
    - url: lol.com
```

```json
[
  { "name": "docs", "url": "lol.com"}
]
```
